INSERT INTO SAMPLE_PROJECT (ID,PROJECT_NAME, DESCRIPTION) VALUES (1,'project-1', 'project-1-DESCRIPTION');
INSERT INTO SAMPLE_PROJECT (ID,PROJECT_NAME, DESCRIPTION) VALUES (2,'project-2', 'project-2-DESCRIPTION');
INSERT INTO SAMPLE_PROJECT (ID,PROJECT_NAME, DESCRIPTION) VALUES (3,'project-3', 'project-3-DESCRIPTION');