server:
  port: 8888


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:h2:file:~/h2data;AUTO_SERVER=TRUE
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    #url: jdbc:h2:file:~/h2data;mode=mysql
    username: postgres
    password: 1234
    #driver-class-name: org.h2.Driver


  jpa:
    # jpa 수행 쿼리 확인.
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: h2
      data-locations: classpath:sql/admin.sql
      mode: always
logging:
  level:
    org.hibernate.type: trace
