server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:mem:admin;mode=mysql
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true  # 웹 콘솔 사용 설정
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    # jpa 수행 쿼리 확인.
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
  sql:
    init:
      platform: h2
      data-locations: classpath:sql/admin.sql
      mode: always
logging:
  level:
    org.hibernate.type: trace
