openapi: 3.0.1
info:
  title: My App API
  description: My App API documentation
  termsOfService: ''
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/resumes/{resumeId}:
    put:
      tags:
        - resume-resource
      operationId: updateResume
      parameters:
        - name: resumeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resume'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resume'
    patch:
      tags:
        - resume-resource
      operationId: partialUpdateResume
      parameters:
        - name: resumeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resume'
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Resume'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resume'
  /api/job-postings/{jobId}:
    put:
      tags:
        - job-posting-resource
      operationId: updateJobPosting
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobPosting'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JobPosting'
    patch:
      tags:
        - job-posting-resource
      operationId: partialUpdateJobPosting
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobPosting'
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/JobPosting'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JobPosting'
  /api/applications/{applicationId}:
    put:
      tags:
        - application-resource
      operationId: updateApplication
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Application'
    patch:
      tags:
        - application-resource
      operationId: partialUpdateApplication
      parameters:
        - name: applicationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Application'
  /api/applicants/{applicantId}:
    put:
      tags:
        - applicant-resource
      operationId: updateApplicant
      parameters:
        - name: applicantId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Applicant'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Applicant'
    patch:
      tags:
        - applicant-resource
      operationId: partialUpdateApplicant
      parameters:
        - name: applicantId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Applicant'
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Applicant'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Applicant'
  /api/resumes:
    get:
      tags:
        - resume-resource
      operationId: getAllResumes
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resume'
    post:
      tags:
        - resume-resource
      operationId: createResume
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Resume'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resume'
  /api/job-postings:
    get:
      tags:
        - job-posting-resource
      operationId: getAllJobPostings
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobPosting'
    post:
      tags:
        - job-posting-resource
      operationId: createJobPosting
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobPosting'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JobPosting'
  /api/authenticate:
    get:
      tags:
        - account-resource
      operationId: isAuthenticated
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
    post:
      tags:
        - user-jwt-controller
      operationId: authorize
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginVM'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JWTToken'
  /api/applications:
    get:
      tags:
        - application-resource
      operationId: getAllApplications
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'
    post:
      tags:
        - application-resource
      operationId: createApplication
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Application'
  /api/applicants:
    get:
      tags:
        - applicant-resource
      operationId: getAllApplicants
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Applicant'
    post:
      tags:
        - applicant-resource
      operationId: createApplicant
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Applicant'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Applicant'
  /api/resumes/{id}:
    get:
      tags:
        - resume-resource
      operationId: getResume
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Resume'
    delete:
      tags:
        - resume-resource
      operationId: deleteResume
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /api/job-postings/{id}:
    get:
      tags:
        - job-posting-resource
      operationId: getJobPosting
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/JobPosting'
    delete:
      tags:
        - job-posting-resource
      operationId: deleteJobPosting
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /api/applications/{id}:
    get:
      tags:
        - application-resource
      operationId: getApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Application'
    delete:
      tags:
        - application-resource
      operationId: deleteApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /api/applicants/{id}:
    get:
      tags:
        - applicant-resource
      operationId: getApplicant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Applicant'
    delete:
      tags:
        - applicant-resource
      operationId: deleteApplicant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /api/account:
    get:
      tags:
        - account-resource
      operationId: getAccount
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserVM'
components:
  schemas:
    Applicant:
      type: object
      properties:
        applicantId:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        phone:
          type: string
    Application:
      type: object
      properties:
        applicationId:
          type: integer
          format: int64
        applicationDate:
          type: string
          format: date-time
        resume:
          $ref: '#/components/schemas/Resume'
        jobPosting:
          $ref: '#/components/schemas/JobPosting'
        applicant:
          $ref: '#/components/schemas/Applicant'
    JobPosting:
      type: object
      properties:
        jobId:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        location:
          type: string
        postedDate:
          type: string
          format: date-time
    Resume:
      type: object
      properties:
        resumeId:
          type: integer
          format: int64
        title:
          type: string
        content:
          type: string
        submittedDate:
          type: string
          format: date-time
        applications:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/Application'
        applicant:
          $ref: '#/components/schemas/Applicant'
    LoginVM:
      required:
        - password
        - username
      type: object
      properties:
        username:
          maxLength: 50
          minLength: 1
          type: string
        password:
          maxLength: 100
          minLength: 4
          type: string
        rememberMe:
          type: boolean
    JWTToken:
      type: object
      properties:
        id_token:
          type: string
    UserVM:
      type: object
      properties:
        login:
          type: string
        authorities:
          uniqueItems: true
          type: array
          items:
            type: string
        activated:
          type: boolean

