INSERT INTO ADMIN_USER (ID, ADMIN_NAME) VALUES (200, 'adminname-1');
INSERT INTO ADMIN_USER (ID, ADMIN_NAME) VALUES (300, 'adminname-2');
INSERT INTO ADMIN_USER (ID, ADMIN_NAME) VALUES (400, 'adminname-3');
